name: dart_1
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.15.1 <3.0.0'
dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  json_annotation: ^4.5.0
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
dependencies: 
  binary: ^2.0.0
  fetch: ^0.0.4
  html: ^0.15.0
  http: ^0.13.4
